"use server";

import { redirect } from "next/navigation";
import { createSupabaseServerClient } from "@/lib/supabase-server";
import { supabase as admin } from "@/lib/supabase";

// The logged-in user's id (or null). Reads the user-scoped session.
async function currentUserId() {
  const supabase = await createSupabaseServerClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();
  return user?.id ?? null;
}

export async function createHousehold(formData: FormData) {
  const name = String(formData.get("name") ?? "").trim();
  const userId = await currentUserId();
  if (!userId) redirect("/login");
  if (!name) redirect("/onboarding?error=" + encodeURIComponent("Enter a household name."));

  // Admin client: creates the household (invite_code is generated by the DB
  // default) and the owner membership. Validated server-side, so RLS stays locked.
  const { data: household, error } = await admin
    .from("households")
    .insert({ name })
    .select()
    .single();
  if (error || !household)
    redirect("/onboarding?error=" + encodeURIComponent("Could not create household."));

  await admin
    .from("memberships")
    .insert({ user_id: userId, household_id: household!.id, role: "owner" });
  redirect("/");
}

export async function joinHousehold(formData: FormData) {
  const code = String(formData.get("code") ?? "").trim().toUpperCase();
  const userId = await currentUserId();
  if (!userId) redirect("/login");
  if (!code) redirect("/onboarding?error=" + encodeURIComponent("Enter an invite code."));

  const { data: household } = await admin
    .from("households")
    .select("id")
    .eq("invite_code", code)
    .maybeSingle();
  if (!household)
    redirect("/onboarding?error=" + encodeURIComponent("That invite code isn't valid."));

  const { error } = await admin
    .from("memberships")
    .insert({ user_id: userId, household_id: household.id, role: "member" });
  if (error)
    redirect(
      "/onboarding?error=" + encodeURIComponent("Couldn't join — you may already be a member.")
    );
  redirect("/");
}
